### ISSUE TITLE
个人页面－智能推荐

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#10]
每两个医生的组合只显示一行，比如纪立农，母义明只显示一行， 合作方式可以多个显示在一块，是否被对方关注现在都是否，好像不对， 具体可以参考PPT上的内容

**Comment by simple-hui** [comment]
是否被对方关注现在都是否 这个有是。已修复。
《每两个医生的组合只显示一行，比如纪立农，母义明只显示一行， 合作方式可以多个显示在一块（待修复，等数据库完善后再进行处理）》

**Comment by Medomino** [comment]
库里专家的关系（偶像，同级，粉丝）这块的数据应该是ready了

**Comment by Medomino** [comment]
再解释一下 先要按朋友级别(更高级别，同级别，更低级别）三个层次 关系从高到底显示，然后同一个朋友只能出现在一行里，合作方式里显示多种合作方式（比如5个大会，2个文章，3个临床试验这样）

eg 现在,张烜 出现了N行， 然后也不知道,张烜 和栗占国到底是同级别还是更高更低级别的朋友关系）

![image](https://user-images.githubusercontent.com/36838827/38666651-00c337b0-3e72-11e8-8986-9d7aed3f9a97.png)

PPT 里是
![image](https://user-images.githubusercontent.com/36838827/38666775-592e8cce-3e72-11e8-9ddb-78f8467e4502.png)

**Comment by Medomino** [comment]
智能合作里不应该有协会这种合作方式 

![image](https://user-images.githubusercontent.com/36838827/38850756-67d9faf2-4245-11e8-9ae5-ef2c233d7b84.png)

**Comment by simple-hui** [comment]
样式已经调整，数据问题周末修复

**Comment by simple-hui** [comment]
数据已修复
