### ISSUE TITLE
数据统计中，时长计算是否正确

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#101]
![image](https://user-images.githubusercontent.com/36838827/41635505-ae8d8758-747b-11e8-9300-a16ca67e750f.png)
以hcc.demo登录进去，看到6.11登录时长超过4000分钟，这个怎么理解？一天最长也不过1440分钟啊，并且目前没有子账号

**Comment by FreeZheng** [comment]
![image](https://user-images.githubusercontent.com/25632017/41694909-345a7c88-753f-11e8-96b6-f64b2fc7ff47.png)

**Comment by FreeZheng** [comment]
前端已做处理，跨日登出的数据 的登陆时长 等于 登陆时间至登时间当天的24点

**Comment by Medomino** [comment]
我咋印象中几分钟不用就自动踢出来了？现在设置的是几分钟来着？

**Comment by FreeZheng** [comment]
已修复，

**Comment by Medomino** [comment]
还是没变化啊，是不影响修改之前的数据么?
