### ISSUE TITLE
又是数据统计，选定公司后无数据显示

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#103]
![image](https://user-images.githubusercontent.com/36838827/41636109-1e45abc2-747f-11e8-8bac-83643c81156a.png)
未选择公司时，正常显示
![image](https://user-images.githubusercontent.com/36838827/41636133-38574746-747f-11e8-9262-c82d5f04f89d.png)
x'ze选择公司后，没有数据了

**Comment by Medomino** [comment]
以上均为super登录

**Comment by FreeZheng** [comment]
已修复

**Comment by Medomino** [comment]
经测试并没有修复啊，而且用户活跃度，模块活跃度两个模块在任何情况下都不显示数据，工具活跃度在选择了公司后不显示数据。

**Comment by PorscheBJ** [comment]
此问题还没有修复。
重复步骤：
1 以super用户登录；【工具活跃度】显示正常。
2 无论选择哪个公司，【工具活跃度】都没有显示数据；
3 从数据库中可以看出，数据库里是有数据的。
![default](https://user-images.githubusercontent.com/38851621/41960178-aaa82994-7a21-11e8-9467-c8bdfa33cd3e.png)

**Comment by Medomino** [comment]
请注意修复

**Comment by FreeZheng** [comment]
已修复
