### ISSUE TITLE
账号设置中，自动关联所属企业

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#104]
是账号管理里面，所属企业现在必须手工录入（非常容易错），其实应该和关联的数据库挂钩。

![image](https://user-images.githubusercontent.com/36838827/41636311-413ed0bc-7480-11e8-89ac-44ee61ff87f0.png)

**Comment by maqunboy** [comment]
需要落数完整在开发。

**Comment by simple-hui** [comment]
已修补
