### ISSUE TITLE
账号设置中需提供按排序功能

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#105]
否则面临大量账号，管理起来很麻烦。请提供按照  名称，类型，关联项目，可见性 的排序功能，

默认排序：
1. 按类型，admin在上面，user在下面，
2.类型相同情况下，按照关联项目排序，
3.关联项目一致后按照可见性排序，
4. 可见性一致后按照名称排序

谢谢
![image](https://user-images.githubusercontent.com/36838827/41636358-8d348d72-7480-11e8-8a9d-e4a6fd0e53a3.png)

**Comment by simple-hui** [comment]
只按照类型排序。顺序为  superadmin -> admin -> user
