### ISSUE TITLE
个性化合作--没有相应合作人选时，显示不正确

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#106]
梁军为例，选择联系方式为文章时：
![image](https://user-images.githubusercontent.com/36838827/41838161-374769e6-7892-11e8-9f6a-595b7d1702a9.png)
选择联系方式为同单位时：
![image](https://user-images.githubusercontent.com/36838827/41838182-4622960c-7892-11e8-8f51-e15b32b0c5a5.png)
两图相同，原因是梁军无同单位合作。但是图没有相应清除之前的显示状态

**Comment by maqunboy** [comment]
已修复
