### ISSUE TITLE
个性化合作中，同单位的联系人不显示

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#107]
有可能与刚才的issue相关，在所有专家的个性化合作中，都不显示同单位的联系人，比如梁军，与沈琳同是北京肿瘤医院的，在梁军的联系人图中也显示有沈琳，但是选择合作方式为同单位后，沈琳并没有相应高亮起来。我猜是这个导致了前面那个显示问题。

**Comment by maqunboy** [comment]
已修复
