### ISSUE TITLE
个性化合作中，“联系时间”项有问题

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#108]
以樊嘉 为例
个性化合作中，选择文章，不选择联系时间，选择tier1，则显示下图：
![image](https://user-images.githubusercontent.com/36838827/41839455-dd1666c6-7895-11e8-9f63-30259f744d33.png)
然而，选择了两年内或两年前，都没有任何人高亮了，明确有问题。感觉是时间划分的问题。以沈锋 为例，其两年内和两年前的文章联系人一样，而和不选择时间的都不一样。请修正

**Comment by maqunboy** [comment]
已修复
