### ISSUE TITLE
个性化合作again--联系方式及列表问题

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#109]
以沈锋为例：
![image](https://user-images.githubusercontent.com/36838827/41839974-2e63d6ac-7897-11e8-8815-d8996bfc2298.png)

选择会议联系人时，“樊嘉”并没有高亮，而下方列表中，显示俩人有会议方面很多合作
![image](https://user-images.githubusercontent.com/36838827/41840025-48a77c80-7897-11e8-9441-011db96b5d07.png)

另外，列表中点击俩人合作的临床试验，居然为空，如果为空不应该显示“临床试验”的。这俩人很可能是有丰富的临床试验合作的。是哪个错了？

![image](https://user-images.githubusercontent.com/36838827/41840117-83e8850a-7897-11e8-9591-9206632922f4.png)

选择列表中和“陈敏山”的合作细节也是临床试验打开为空。同时有很多人的是正常显示的。。。

**Comment by Medomino** [comment]
下图中，选择了临床试验，“樊嘉”没有高亮，但是俩人的联系细节列表中，有临床试验

![image](https://user-images.githubusercontent.com/36838827/41840995-bd0ba6a8-7899-11e8-9a3b-9ef43e996072.png)

**Comment by maqunboy** [comment]
合作方式临床试验  需要数据库配合  NCT01681446  这个没有查询到临床试验信息，但是在edges_details 存在这样的数据。属于数据库问题。

**Comment by maqunboy** [comment]
已修复

**Comment by Medomino** [comment]
ct.gov 里有这个NCT01681446 试验记录的
![image](https://user-images.githubusercontent.com/36838827/41961404-f9affa28-7a24-11e8-98cc-4dee2622d5ac.png)

**Comment by PorscheBJ** [comment]
能否提供一下你们选取这个数据的SQL，我们跟踪一下是否是数据的问题。谢谢

**Comment by maqunboy** [comment]
已修复，少查了一张表。
