### ISSUE TITLE
医生个人页面－学术活动

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#11]
1.现在的学术活动缺少个数的summary, Navigator 1.0里有文章个数，临床试验个数等
2. 另外，医生个人页面－学术活动（文章）里少了PPT里的45页的内容，publication trend, publication tier, Top journal ； 
3.临床试验的数据好像不对，主要研究者都是母义明＃＃＃潘长玉。 BTW， 我们后台数据里的＃＃＃是And的连接符合，在前段的显示的时候请劳驾替换成逗号或者分号之类的符号
4. 各个数据的链接好像链接不出去，只能回到仪表盘的页面

**Comment by simple-hui** [comment]
问题1已修复 问题2 ppt里没有45页 我看的是讨论后的版本 20170812的那个 问题4 已修复

**Comment by simple-hui** [comment]
问题3进行重新校验数据 已修复
