### ISSUE TITLE
个性化合作中，指南的合作人没有显示，去掉学会作为合作方式

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#110]
以秦叔逵为例，联系人合作列表中，与樊嘉的合作没有指南，选择合作方式为指南后也没有人高亮，甚至那个晃动的过程都没有。但实际上，数据库中有俩人的共同合作指南
![image](https://user-images.githubusercontent.com/36838827/41841387-bb78484a-789a-11e8-976e-dfc9e60022bc.png)

![image](https://user-images.githubusercontent.com/36838827/41841481-f7b5451a-789a-11e8-9cb6-d60ed662dff1.png)
![image](https://user-images.githubusercontent.com/36838827/41841487-fdf05ba4-789a-11e8-9f53-3d78972377aa.png)

学会并没有作为合作方式进行计算，在合作方式的选项中也请相应去掉学会

**Comment by Medomino** [comment]
指南这个确认了一下也没有数据，所以麻烦像学会一样去掉，不好意思了

![image](https://user-images.githubusercontent.com/36838827/42076022-fc9ec0a2-7ba5-11e8-8a50-a4d2024bbb39.png)

**Comment by maqunboy** [comment]
已修复
