### ISSUE TITLE
chinadrugtrials 的链接问题

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#111]
测试账号：hcc.demo
密码：hcc123

点击首页的红框里（截图一）的链接，结果显示截屏二
查过chinadrugtrials.csv （截图三）里的链接是正常能显示的
![image](https://user-images.githubusercontent.com/36838827/41970970-566850a2-7a3f-11e8-9031-58383bd2f9c8.png)
![image](https://user-images.githubusercontent.com/36838827/41970983-626a074c-7a3f-11e8-8558-02e748682899.png)

![image](https://user-images.githubusercontent.com/36838827/41971002-7c9d97f0-7a3f-11e8-8807-723d6262196d.png)

**Comment by maqunboy** [comment]
取的是friendsnews的url请数据修复这里的地方。
