### ISSUE TITLE
仪表盘的竞争格局

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#112]
测试账号：hcc.med
密码：hcc123
仪表盘里竞争格局最右边的专家显示，但点击右下角的“更多”后显示的不一致

**Comment by simple-hui** [comment]
已修补。

**Comment by Medomino** [comment]
![image](https://user-images.githubusercontent.com/36838827/42069705-c579132c-7b85-11e8-8366-8b79d10e7679.png)

**Comment by FreeZheng** [comment]
已修复
