### ISSUE TITLE
rising star 导出Excel的表头

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#113]
导出的excel 内容和格式请和 下面这个表保持一致， 现在的表头是数据后台表的表头，不适合用户直接使用，谢谢

![image](https://user-images.githubusercontent.com/36838827/42012630-da3163b0-7acb-11e8-931a-eea06f636333.png)

**Comment by simple-hui** [comment]
已修复

**Comment by Medomino** [comment]
表头已经修复，谢谢。但是excel 表里的内容和web前端的内容不一致 

![image](https://user-images.githubusercontent.com/36838827/42075294-df454c22-7ba2-11e8-9550-f8bf773629af.png)

**Comment by simple-hui** [comment]
已修复。
