### ISSUE TITLE
我的关注对专家列表进行网络个性化分析，点堆积在一起

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#115]
测试账号：hcc.med
密码：hcc123
我的关注里的”Demo HCP List“ ->个性化分析，如下图
![image](https://user-images.githubusercontent.com/36838827/42018409-9638b348-7ae4-11e8-8879-b2e92b0dd5cd.png)

**Comment by FreeZheng** [comment]
已修复
