### ISSUE TITLE
个人页面竞争合作里大会合作方式图里不显示

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#116]
测试账号：hcc.med
密码：hcc123
这个专家和Bayer 有大会活动，前端和后台数据都显示有，但是图里没有 
![image](https://user-images.githubusercontent.com/36838827/42025727-d994a332-7af7-11e8-8e56-67053175d8e7.png)

![image](https://user-images.githubusercontent.com/36838827/42025650-ad06ccb4-7af7-11e8-8352-db22768d9694.png)

![image](https://user-images.githubusercontent.com/36838827/42025628-a01d29d0-7af7-11e8-980c-251523686f5c.png)

![image](https://user-images.githubusercontent.com/36838827/42025610-91bc605e-7af7-11e8-9657-ddea8b994104.png)

**Comment by maqunboy** [comment]
这里图，取的是competitor_doctor——》meeting不为0的。下面的表格取的是competitor_session。

**Comment by maqunboy** [comment]
确认数据问题，关闭。
