### ISSUE TITLE
仪表盘竞争格局左边的图在competitor_session没有数据的情况下不显示

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#117]
测试账号： bc.demo
测试密码：bc123
仪表盘竞争格局坐标的图在competitor_session没有数据的情况下不显示， 但是是有competitor_artical 和 competitor_CT 的数据的，所以理论上不应该完全不显示。 PS 个人页面的就能正常显示
![image](https://user-images.githubusercontent.com/36838827/42130526-6dcf4ace-7d1a-11e8-835c-ba2fc496d580.png)
![image](https://user-images.githubusercontent.com/36838827/42130530-86c09858-7d1a-11e8-92e4-dbe0e00df391.png)

**Comment by maqunboy** [comment]
已修复
