### ISSUE TITLE
主题颜色问题

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#12]
医生细分，和专家个人页面里的学术活动这些图请改用主体颜色的图

**Comment by FreeZheng** [comment]
没看懂什么意思

**Comment by simple-hui** [comment]
已解决

**Comment by Medomino** [comment]
图标多了开始颜色分不清的问题。 请把颜色调至肉眼能区分的程度
![image](https://user-images.githubusercontent.com/36838827/37890915-e479e8a8-3104-11e8-9c9f-e93db8efd227.png)

**Comment by simple-hui** [comment]
已修复
