### ISSUE TITLE
网络分析-战术智能推荐

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#15]
1. step2里的icon 图标显得比其他的都大，请调至相似大小
2. 每一步下面的解释语句，能否靠左对齐，目前居中的显示方式显得比较乱，且行间距稍微调宽一些
3. step 2 经常死机，且每次添加专家最多只能加10个么？请改成添加所有，且是添加的关系，不是替换的关系

**Comment by FreeZheng** [comment]
step2 icon已改小
左对齐，间距加大

**Comment by FreeZheng** [comment]
死机问题解决，专家默认是10个/页，可以改变显示条数，一次添加更专家；因为全选按钮只针对于当前页；请确认如何修改？
