### ISSUE TITLE
战术推荐添加医生困难

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#18]
在战术推荐中，如果想通过搜索添加医生，需要每一个去选择添加，非常难用
![image](https://user-images.githubusercontent.com/36838827/37749821-be202e62-2dc4-11e8-91c6-bd09eafe73ad.png)

**Comment by Medomino** [comment]
另外，选择现成的医生列表时，假设列表有上百人（很正常），第一需要明白去选择每页的显示人数，否则是不会选择第二页的那些医生（这个问题在各个列表的场景都存在，这种处理是比较让人困惑的，大部分人会默认打勾了全选就选择了所有人而不是只有第一页的人），第二全选后滚动到最下方才能确定，很不方便，请改进

**Comment by FreeZheng** [comment]
已修复，取消分页，默认全部是一页，增加滚动条；
增加批量添加按钮;
