### ISSUE TITLE
医生个人页面

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#19]
1.合作者改成合作单位
![image](https://user-images.githubusercontent.com/36838827/37806470-1db31266-2e7b-11e8-8ccb-2a829231df20.png)

2. 朋友圈最新动向应加一列显示该动向的医生姓名，同时更改排序为最新的最先显示
3.请把拜访密器改名为拜访助手
4. 个人的文章列表排序规则应为：按时间顺序，最新的在最前面
5. 个人中心网络页面下，选择联系方式为”同单位“时，显示无变化。
6. 文章列表相关的各处，作者顺序中的”$"均改成"/"
7. 搜索中，医院信息搜索无效，不返回任何结果，请改正

**Comment by Medomino** [comment]
搜索功能大面积有问题，请测试每个搜索模块，现在除了医生信息有返回结果其余要么不返回任何结果，要么返回结果没法看，如下图
![image](https://user-images.githubusercontent.com/36838827/37806712-67bf9ffe-2e7c-11e8-8410-74176d96ee36.png)

**Comment by simple-hui** [comment]
1已解决

**Comment by simple-hui** [comment]
2 已经增加医生姓名，数据需要处理一下。
3 拜访已修复

**Comment by Medomino** [comment]
4里面除了同单位筛选无变化外，联系时间筛选也无变化，联系强度筛选缺失（PPT上联系强度是按排名分类的）

**Comment by simple-hui** [comment]
2已增加姓名

**Comment by maqunboy** [comment]
5 已解决

**Comment by maqunboy** [comment]
搜索功能完成
