### ISSUE TITLE
医生集合

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#2]
我提交了一个bug

**Comment by Medomino** [comment]
“筛选”列名请根据筛选内容命名， 默认列名为“综合学术分数”
![image](https://user-images.githubusercontent.com/36838827/37890718-30ce9b3c-3104-11e8-97c2-78f8149f3b2d.png)

**Comment by Medomino** [comment]
2. 这个地方请默认改成100一个一页，采用滚动的方式呈现
![image](https://user-images.githubusercontent.com/36838827/37900148-f1acad7e-311f-11e8-90a9-71b5ef264b49.png)

**Comment by simple-hui** [comment]
已修复

**Comment by Medomino** [comment]
我这边看第一个问题没有修复。现在那一列还是显示“筛选”，而不是筛选的内容比如”综合学术能力“等这些。 
第二个问题缺失修复了，谢谢！ 页面请相应的往下拉，多显示一些专家。

![image](https://user-images.githubusercontent.com/36838827/38080031-f46b018c-3372-11e8-95bd-d8e83d372a77.png)

**Comment by simple-hui** [comment]
已修复。
