### ISSUE TITLE
“我的关注”页面--医生分组

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#21]
![image](https://user-images.githubusercontent.com/36838827/37890557-89b0ef8a-3103-11e8-9b69-a1f6a6c24f3b.png)
按城市/地区 等等分组，选择后城市/地区等应只显示当前数据中存在的部分，不应该显示数据全集中的所有可能性。如图，当前列表中并没有“江门”的医生，导致困惑，并且城市列表很长

**Comment by simple-hui** [comment]
已经缩短长度。因为考虑到除了城市外的其他分组。没有太短

**Comment by maqunboy** [comment]
问题已修复
