### ISSUE TITLE
网络分析战术推荐 和个人网络图请设置成最多只动画一次

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#22]
现在的网络分析战术推荐 和个人网络图每一个操作都有动画。 本来图的展现就不是很清楚，一动的话就更是让人觉得晕，所以请设置成最多第一加载是动的，其他操作不要有动画，谢谢

**Comment by FreeZheng** [comment]
动画是说明在绘制图表，无法消除，绘制是有一个过程的，我可以加大绘制的速度，目前已修复加载速度。
