### ISSUE TITLE
战略推荐和战术推荐医生列表里添加医生姓名链接个人主页和分数排序功能

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#27]
可点击医生姓名链接到其个人主页，可按这三个分数，分别排序(类似excel 加个箭头，点击箭头从高到低分数排序，再次点击箭头，分数从低到高排序）
![image](https://user-images.githubusercontent.com/36838827/37954278-e64c35fe-31d7-11e8-95fd-1d3fc8633124.png)

**Comment by simple-hui** [comment]
已修复

**Comment by Medomino** [comment]
谢谢。我目前看战略里加好了，但是战术里还没有弄好是吧？

**Comment by simple-hui** [comment]
战术第四步智能推荐增加完成
