### ISSUE TITLE
个人页面下的竞争合作者图例和内容缺失

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#28]
请把上面这张图的图例改成和下面那个一致。 另外合作方式和合作内容缺失（且请在合作内容上提供链接）

![image](https://user-images.githubusercontent.com/36838827/38079248-0723f7e0-3371-11e8-8dd3-c4564291e64e.png)

![image](https://user-images.githubusercontent.com/36838827/38079157-d2f24fbc-3370-11e8-8091-71f869dab6e8.png)

**Comment by FreeZheng** [comment]
图例已修复

**Comment by simple-hui** [comment]
目前数据有问题

**Comment by maqunboy** [comment]
问题已修复
