### ISSUE TITLE
战术推荐第三步无法从我的关注医生列表里添加专家

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#30]
战术推荐第三步无法从我的关注医生列表里添加专家，请修改成和第二步的添加操作一致。 当时见面讨论的时候强调过第三步和第二步其实在操作上没有啥区别，只是目的不一样。可能我们前段时间没有仔细用，没有发现第三步其实不能从我的关注医生列表里添加专家。 麻烦请修改一下这里，谢谢了。

**Comment by simple-hui** [comment]
已修复
