### ISSUE TITLE
医生细分上色缺少多选功能

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#31]
如PPT里要求
![image](https://user-images.githubusercontent.com/36838827/38081880-b3de4430-3377-11e8-9097-b0b8d49e524e.png)

![image](https://user-images.githubusercontent.com/36838827/38081812-89bca656-3377-11e8-8234-a253f1811435.png)

![image](https://user-images.githubusercontent.com/36838827/38081729-4c5934f0-3377-11e8-9397-febfad5ca49d.png)

**Comment by Medomino** [comment]
2. 上色颜色请默认有一些主题颜色供挑选。 要不然一下子就到一个巨大的色板上，很可能鼠标稍微挪一挪颜色就不对了，一般用户也不会去记颜色代码对应的颜色。其实我们在PPT里是有要求批量自动上色的
![image](https://user-images.githubusercontent.com/36838827/38082094-378a874e-3378-11e8-815d-fec5eb8caad1.png)

**Comment by FreeZheng** [comment]
多选和推荐色块已修复
