### ISSUE TITLE
网络分析-个性化全屏保存图片不完整

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#33]
如图对比所示

![image](https://user-images.githubusercontent.com/36838827/38083768-2c7ce612-337d-11e8-8571-942a3a4cb2b0.png)

![image](https://user-images.githubusercontent.com/36838827/38083784-36735070-337d-11e8-9449-6a79b7680772.png)

**Comment by FreeZheng** [comment]
已修复
