### ISSUE TITLE
高级搜索页面

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#34]
1.  功能区 与高级搜索的切换按钮上， 请把“简约模式”这几个字改成 “主页面”
2. 高级搜索里 这些搜索类型，请去掉橘黄的底色，字体大小颜色换成和“个性化智能合作”这些子标题一样
3. 高级搜索里键入值得地方，需要提供下拉提示菜单，比如输入“王”，下拉里呈现所有姓王的医生

![image](https://user-images.githubusercontent.com/36838827/38126205-9fc6a8e8-3421-11e8-85e9-2093f5f21b4b.png)

![image](https://user-images.githubusercontent.com/36838827/38126355-a75cf688-3422-11e8-8b10-840bc5de5923.png)

**Comment by simple-hui** [comment]
1、2已修复。 3暂不解决。
