### ISSUE TITLE
rising star

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#39]
1. 职称这一列应该是”主任医师，副主任医师“这一列，不是行政职务（主任，副主任）这一列
2. 最后一列显示rising star potential  (高潜力，中潜力，低潜力）这些值
3，医生姓名需要能链接到个人主页
4. 点击左上角的 ”Rising star" 需要在新的页面显示所有的 rising star flag 标记“Yes" 的人， 排序和dashboard 上的优先级一致（rising star flag 标记”Yes" 的， rising star potential 高潜力 > 中潜力 > 低潜力, 然后 按appeal) 
5. 新页面的内容比 dashboard 里多这些列：杰出青年基金（raising_star_eysf，显示该基金的题目，点击链接到该基金）；青年委员会任职（raising_star_ya ，显示该学会名称和角色）；个人关系网络（raising_star_big_relation，显示专家名字并提供链接到个人页面）；专家号召力（appeal)。 多个值用；分号连接

![image](https://user-images.githubusercontent.com/36838827/38594044-19b020ea-3d77-11e8-9229-a3d2848a0265.png)

**Comment by simple-hui** [comment]
已修复

**Comment by Medomino** [comment]
学会和任职应该合在一列里，另外现在显示的不是任职，任职应该是doctor_association 里利用医生ID和学会ID锁定role 这一列

![image](https://user-images.githubusercontent.com/36838827/38667377-da6cce12-3e73-11e8-9dcd-a2caea54b9ad.png)

![image](https://user-images.githubusercontent.com/36838827/38667755-ccd59616-3e74-11e8-8644-6893a5108c38.png)

**Comment by Medomino** [comment]
另外一个小地方， 仪表盘和点进去的rising star rational 应该改成 rising star 潜力

**Comment by Medomino** [comment]
学会任职这一列还是错的，且没有和学会合并在一起

**Comment by Medomino** [comment]
目前显示未按专家号召力排序

**Comment by simple-hui** [comment]
Rising star 潜力 文字已经在控制台以及点进去的页面更改

**Comment by maqunboy** [comment]
已解决
