### ISSUE TITLE
竞争格局

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#4]
1. dashboard页面视图中图例和图挤在一起
2. 全页面视图中，人/公司的分数的小数位过多，不保留小数
3. 全页面视图和dashboard视图中，KOL Name 应提供人的链接,合作内容栏，应提供相应内容的链接，时间应保留月份

**Comment by simple-hui** [comment]
dashboard页面视图中图例和图加大了间隙
图的小数都已经解决
KOL Name 应提供人的链接,合作内容栏 都已经增加链接  月份 已保留

**Comment by Medomino** [comment]
仪表盘的竞争格局点击More进去，目前柱状图上只能看见三个专家有数据，请检查

**Comment by FreeZheng** [comment]
已修复
