### ISSUE TITLE
个人页面-拜访助手

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#40]
1“个人最新动向” 和“朋友圈最新动向” 请相应改成没有底色的字体，和以前的要求一致
2 会议的角色好多都是空的，为啥？

![image](https://user-images.githubusercontent.com/36838827/38666946-c27a3426-3e72-11e8-9f1c-a2f8425c3b74.png)

**Comment by Medomino** [comment]
3. 临床和文章里的角色里其他是从哪儿取的值？
![image](https://user-images.githubusercontent.com/36838827/38667165-4bb73978-3e73-11e8-87e5-ac8c269c3158.png)

**Comment by simple-hui** [comment]
1 已解决

**Comment by simple-hui** [comment]
这个是不是已经没有了 issues 关了。有问题再开
