### ISSUE TITLE
上色和筛选里，医生级别，职位

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#42]
1.上色和筛选的医生级别应该是doctor表的 KOL那列，现在这列是错的医生的职称。排序请按照（从高到低：国际级专家，国家级专家，区域级专家，省级专家，关键医生，退休专家，其他等这样的顺序排列下拉菜单）
2. 医生职位排序请按照从高到低（院长，副院长，主任，副主任，其他等）这样的在下来菜单排列

![image](https://user-images.githubusercontent.com/36838827/38843900-b5deec16-4223-11e8-8e8f-323c098eb4f4.png)

**Comment by simple-hui** [comment]
嵩哥改

**Comment by FreeZheng** [comment]
排序等群哥修复
