### ISSUE TITLE
高级搜索

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#43]
城市级别搜索不出医生
![image](https://user-images.githubusercontent.com/36838827/38850284-512dbdb8-4243-11e8-98c3-c7c3c26df535.png)

**Comment by Medomino** [comment]
2. 点击下来菜单后，无法不选择值 ， 且不能删除这模块的设置（除非推出重来）

![image](https://user-images.githubusercontent.com/36838827/38850334-8e0068f8-4243-11e8-9e59-be03b153488f.png)

**Comment by maqunboy** [comment]
1问题解决。二问题嵩哥帮忙加个默认全部  传空即可。

**Comment by simple-hui** [comment]
2已修复
