### ISSUE TITLE
个人页面-学术活动-国家自然科学基金

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#44]
1. 基金金额显示是少乘了一个0

![image](https://user-images.githubusercontent.com/36838827/38854672-d1802ba8-4253-11e8-8b99-3bb9ef440901.png)

2. 另外，缺少基金类型这个字段

![image](https://user-images.githubusercontent.com/36838827/38854715-f9c32b1a-4253-11e8-94c4-cb6c1b14736a.png)

**Comment by Medomino** [comment]
高级搜索里的基金类型和库里的基金类型不一致
![image](https://user-images.githubusercontent.com/36838827/38855917-877d1de6-4257-11e8-9134-2f8359f9160a.png)

**Comment by simple-hui** [comment]
1已修复

**Comment by maqunboy** [comment]
已修复
