### ISSUE TITLE
竞争情报的坐标轴应固定

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#45]
![image](https://user-images.githubusercontent.com/36838827/38857534-1630d7d6-425c-11e8-8136-b209fcf253a7.png)
竞争情报的坐标轴应按库中所有医生中个人分项总分最高值固定下来，否则会产生误导，以为图中医生与竞品合作很强，其实合作很少，只是坐标轴自动调整导致了误解。

**Comment by FreeZheng** [comment]
不建议修改固定值，如果总分很高，当前显示的很少，根本看不清差别，和具体的大小。建议保留自适应坐标值

**Comment by Medomino** [comment]
还是认为应该修改，这个有两重比较，一个是医生之间的比较，就会形成误导，以为这个医生和某企业合作很多，另外是同一个医生和不同企业的比较，同样会形成误导。看不清差别确实是问题，有没有可能用类似医生细分里的可调坐标轴来实现，初始是按照库里最大值放，如果想看清楚，可以自己调坐标轴

**Comment by FreeZheng** [comment]
可以，但是需要一个库里的最大值

**Comment by maqunboy** [comment]
已经给出最大值MAX

**Comment by Medomino** [comment]
最大值MAX是取competitor_doctor 表里某个医生的最大值么？ 为啥这个图超出坐标轴了？
测试账号： bc.demo
密码：bc123
医生徐兵河 的个人页面里的竞争者合作

![image](https://user-images.githubusercontent.com/36838827/42148596-7347eb96-7e05-11e8-855b-b6ea9813c300.png)

**Comment by maqunboy** [comment]
已修复
