### ISSUE TITLE
dashboard的竞争格局下钻

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#48]
![image](https://user-images.githubusercontent.com/36838827/39162905-77c3e012-47aa-11e8-87e7-3d15a173af7a.png)
进入dashoboard的竞争格局，点击红框部分，请显示如下格式
![image](https://user-images.githubusercontent.com/36838827/39162932-a3e628e4-47aa-11e8-8f49-40269f4f6bf6.png)
也即以友商为单位显示竞争格局，而不是以专家为单位显示，把友商的每次赞助事件为一行，其所有参与专家集中列出来，并点击下钻至专家个人页面的竞争格局部分。默认排序为时间

**Comment by Medomino** [comment]
![image](https://user-images.githubusercontent.com/36838827/39163057-4c0c415c-47ab-11e8-8e58-d64b38fc2808.png)
点击红框内时，应下钻至该专家的个人页面中竞争格局部分

**Comment by FreeZheng** [comment]
右侧图点击下纂已修复

**Comment by FreeZheng** [comment]
表格显示字段问题，辉哥具体看看吧

**Comment by simple-hui** [comment]
这个还有什么问题？

**Comment by maqunboy** [comment]
不予以解决
