### ISSUE TITLE
搜索功能--一系列搜索有问题

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#49]
![image](https://user-images.githubusercontent.com/36838827/39163381-d087dbfc-47ac-11e8-8cf8-0c63bfa5429c.png)
在学会搜索中，如果选择青年委员，则无论是否选择级别都没有结果。这不可能。请改正。
如果选择青年委员后，清除青年委员，选择国家级，则无结果，这不对，请改正

在会议活动搜索中，无论主办方和赞助方填写什么内容，无论时间如何定义，无论角色如何，无论级别，搜索结果不变，请改正。

我现在感觉搜索一个问题是，只要之前出现了无结果，后面再怎么搜都无结果了。在医院里，首先单独搜索三甲，没问题，如果合并华北地区，则无结果（肯定不对），然后去掉华北地区，单独搜索三甲，也变成无结果了

搜索里面，按医院信息，医院名称那个地方是允许按逗号分隔的，意思是“或”对吧，实践起来貌似是“且”.例如，同时搜索北大人民,协和，是无结果，单独搜索两个都有正确结果

文章搜索按杂志级别无结果，按关键词无结果，按作者顺位，死机

**Comment by simple-hui** [comment]
搜索又过了一遍。除数据库没数据外 目前我们没有发现问题，如果还有问题。 请告诉我们一下 搜索项 是怎么搜的
