### ISSUE TITLE
合作方式显示“临床”的一律改成“临床试验”

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#51]
RT, 谢谢

**Comment by simple-hui** [comment]
已修复

**Comment by Medomino** [comment]
![image](https://user-images.githubusercontent.com/36838827/39900877-733694b8-54f7-11e8-9389-ad988a0d42f1.png)

**Comment by Medomino** [comment]
![image](https://user-images.githubusercontent.com/36838827/39900913-9d58af10-54f7-11e8-91bb-68218a2fa763.png)

**Comment by simple-hui** [comment]
已修复。
