### ISSUE TITLE
个人智能合作弹窗内容按时间排序

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#56]
pubmed, clinical trial, event  这些都能按date 排出来。只有万方是按年的，请排在pubmed 文章的后面，比如pubmed 最后一篇文章是2017-01-01的，那么万方2017的所有文章排在这篇文章的后面， 然后pubmed 2016年的
![image](https://user-images.githubusercontent.com/36838827/39683566-d6130f56-51e8-11e8-8635-282cb46f7cee.png)

**Comment by simple-hui** [comment]
已修复
