### ISSUE TITLE
仪表盘竞争情报分析里的合作内容总是有空白的

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#57]
RT，我检查了后台数据截屏里的这个人是都有文章ID

![image](https://user-images.githubusercontent.com/36838827/39789029-ef20ce52-535f-11e8-9ddb-aab294ddbd4f.png)

![image](https://user-images.githubusercontent.com/36838827/39789040-05f22bc6-5360-11e8-80c6-b80c9d5512f5.png)

**Comment by maqunboy** [comment]
已修复
