### ISSUE TITLE
医生细分

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#6]
1. 鼠标指向坐标轴不应显示“undefined”
2. x轴，y轴均应允许按联系度等，请参考1.0版本相关参数
3. 圈选后添加至现有列表时，实际为替换了现有列表的内容，是否可以改成添加？如果只能替换，则应有提示
4. 在细分中进行筛选后，细分图更新略慢，应加loading
5. 在细分中，进行上色后，图例显示有问题，有逗号
6. 细分的筛选和上色中，必须先选区域-省市-城市，可是为什么医院可以直接选取？为什么不能都直接选取？
7. 在细分的全屏视图下，只有xy轴的选择有用，其余按键均不显示在全屏状态下。需改正

**Comment by FreeZheng** [comment]
1，已修复
2，已添加
3，已修复为添加
4，已添加loading
5，已修复
6，无需修复    区域-省-市是级联菜单，需要有上级菜单，参照1.0 一样的
7，已修复

**Comment by Medomino** [comment]
经过测试，3仍然是替换

**Comment by FreeZheng** [comment]
问题已修改，只是没有发版
