### ISSUE TITLE
个人网络图筛选结果不一致

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#60]
请检查edges_details 的那张表是不是没有D1， D2都搜索一遍，导致筛选合作类型（文章等），一个专家的网络图有，对应的专家网络图下筛选则没有

![image](https://user-images.githubusercontent.com/36838827/39900401-37bb0fde-54f4-11e8-96a8-3503f03a2dd8.png)
![image](https://user-images.githubusercontent.com/36838827/39900403-3c872e8a-54f4-11e8-99d9-3ae01c13ae9b.png)

**Comment by FreeZheng** [comment]
已修复
