### ISSUE TITLE
高亮信息前端显示和表里的内容不一致

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#61]
表里每个医生每子类项最多5条信息
![image](https://user-images.githubusercontent.com/36838827/39912151-59d3c75a-5530-11e8-8e1e-e9a62d316aba.png)
![image](https://user-images.githubusercontent.com/36838827/39912170-68342920-5530-11e8-97ba-afe9c0addb90.png)

**Comment by simple-hui** [comment]
已修复
