### ISSUE TITLE
战术推荐的第二，第三步，从搜索和医生列表筛出医生列表后，直接勾选确定添加，现在太复杂了，每次都需要选好多遍

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#62]
都设计成下面这样，不需要右边那个框，筛出列表后，直接可以批量勾选或者勾选几个人，然后确定即可添加

![image](https://user-images.githubusercontent.com/36838827/39912526-9a5d0a06-5531-11e8-8852-37182e40a668.png)

**Comment by FreeZheng** [comment]
功能已实现，而且事先你们已确认此方案，修改的成本较大，所以暂无需修改
