### ISSUE TITLE
普通用户被设置可见性后，个人网络图消失

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#64]
可用以下账号重现问题用户名dia.top
密码dia123
![image](https://user-images.githubusercontent.com/36838827/39976741-e67a9a56-5767-11e8-8aff-bff883061d3b.png)

**Comment by maqunboy** [comment]
已修复

**Comment by Medomino** [comment]
点进去依旧是加载不出来

![image](https://user-images.githubusercontent.com/36838827/40226658-d4141c3e-5abe-11e8-9116-a3de39caf522.png)

**Comment by maqunboy** [comment]
已修复
