### ISSUE TITLE
个人页面拜访助手--类型错误

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#66]
friendnews 里 source 类型是Pub, 显示却是临床

Souce里
ASSO ： 学会
CT ：临床试验
EVENT：大会
GUIDE ： 指南
PUB ： 文章

![image](https://user-images.githubusercontent.com/36838827/40152496-0d931c10-59b8-11e8-8536-d246fdd06868.png)

![image](https://user-images.githubusercontent.com/36838827/40152480-ffafe290-59b7-11e8-8b3a-f84670e867bf.png)

**Comment by maqunboy** [comment]
![image](https://user-images.githubusercontent.com/18322323/40153973-c4f1bb5e-59be-11e8-9f4c-c880a560c748.png)
麻烦修改数据库内数据，属于数据库落数问题。
