### ISSUE TITLE
1.0里 我的关注模块可将专家列表添加到医生细分和网络图-个性化里

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#68]
![image](https://user-images.githubusercontent.com/36838827/40162911-ed1da40c-59e7-11e8-978f-b6232331d100.png)
![image](https://user-images.githubusercontent.com/36838827/40162930-fdb0be44-59e7-11e8-88a7-7363d47a86ee.png)
![image](https://user-images.githubusercontent.com/36838827/40162944-0c1a52d8-59e8-11e8-91a3-1ab5483f2e74.png)

**Comment by FreeZheng** [comment]
已修复
