### ISSUE TITLE
医生个人主页

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#7]
医生级别应该是“国家级专家，区域级专家”等，不是专业职称

**Comment by simple-hui** [comment]
已解决

**Comment by Medomino** [comment]
目前的医生个人页面缺少了Navigator1.0 里的概要信息和高亮信息。 请在红色框位置添加一个模块： 默认显示概要信息， 点击“高亮信息”后进入高亮信息页面。
![image](https://user-images.githubusercontent.com/36838827/37890116-e5b82c3c-3101-11e8-978e-f082045b2590.png)

**Comment by Medomino** [comment]
![image](https://user-images.githubusercontent.com/36838827/37890135-fa988070-3101-11e8-8a9b-761317cad608.png)

**Comment by simple-hui** [comment]
已添加 高亮信息再议

**Comment by Medomino** [comment]
看见添加概要信息了， 但是字体太小了。
科室信息不对
协会请按纵向排列
高亮信息有什么问题吗？
![image](https://user-images.githubusercontent.com/36838827/38125437-0fc8e6ca-341c-11e8-98b1-104c53a13c49.png)

**Comment by simple-hui** [comment]
已修复。 高亮信息群哥会沟通

**Comment by Medomino** [comment]
高亮信息放在概要信息那个模块里 ，改名成“概要和高亮信息”

**Comment by simple-hui** [comment]
高亮已修复
