### ISSUE TITLE
个人页面里的个性化合作 ”是否被对方关注“

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#73]
是否被对方关注里 ”是否“的标准是排序前30% ， 但是不知道你们是否还记得咱们电话会议的时候说过1/1 ，1/2，1/3 这种情况是例外，虽然他们超过30%，但是由于分母小，还是应该归为 ”是“ 

![image](https://user-images.githubusercontent.com/36838827/40345292-2e709716-5dcb-11e8-9adc-5106543490ea.png)

**Comment by maqunboy** [comment]
发版后验证
