### ISSUE TITLE
HCC项目中，智能合作中，某些人的合作经历不显示

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#75]
如，董家鸿与樊嘉的临床试验和大会，点击都没结果，如图
![image](https://user-images.githubusercontent.com/36838827/40894704-0676bb6a-67de-11e8-9cd6-c30f7f01a7d6.png)
董家鸿与郑树森的也是这样。

**Comment by maqunboy** [comment]
已修复
