### ISSUE TITLE
个人页面-文章里新加的三个图

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#77]
1. Pub trend 和图例重叠，请将图例下移一些
2. 第一个图现在显示有问题， 比如下图梁军2018，2017年也有文章，但是图上只显示2015年
3. 第二个图请标上各表饼图的文章数量
4. 第三个图，坐标轴去掉0.5 这个尺度（不会出现发半篇文章的情况），另外请从高到底排序
谢谢

![image](https://user-images.githubusercontent.com/36838827/40953965-dffae4ac-68b4-11e8-9662-b435f354f87c.png)

**Comment by simple-hui** [comment]
2已修复

**Comment by simple-hui** [comment]
4 从高到低已修复

**Comment by FreeZheng** [comment]
都已修复

**Comment by Medomino** [comment]
谢谢， 上面的问题都OK了，但是第一个图的时间反了。 

![image](https://user-images.githubusercontent.com/36838827/41264841-892f7e4a-6e21-11e8-898a-a89ca0ca9b87.png)

**Comment by simple-hui** [comment]
已解决
