### ISSUE TITLE
链接方式（”详细链接“的不需要额外这个字段，都直接改成title 或者人名链接）

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#8]
比如仪表盘的最新动态，不需要“详细链接”这个字段，自己在主题上链接
医生集合，不需要“详细链接”，直接在医生名字上链接
拜访密器，不需要“详细链接”，直接在主题上链接
等等类似情况，用于节约显示空间

**Comment by simple-hui** [comment]
已修改。如果有遗漏 请再指出。
