### ISSUE TITLE
网络图个性化--过滤条件没有反映

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#80]
选了过滤条件Bayer, 确定后还是所有的点

![image](https://user-images.githubusercontent.com/36838827/41020881-1248fd1c-6997-11e8-8896-2abfe592ed16.png)

![image](https://user-images.githubusercontent.com/36838827/41020919-33dd08a6-6997-11e8-8b7b-33aece86a320.png)

**Comment by maqunboy** [comment]
问题已修复
