### ISSUE TITLE
仪表盘rising star点进去现在排版有问题

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#87]
请看截屏，在MAC电脑上登入的。
![image](https://user-images.githubusercontent.com/36838827/41222519-b4107264-6d99-11e8-9ff3-5b429dc9990a.png)

**Comment by simple-hui** [comment]
已修复。

**Comment by Medomino** [comment]
我们这边显示还是有问题，找了两台机器测试，好奇怪

**Comment by simple-hui** [comment]
再看一下 没问题了。
