### ISSUE TITLE
医生个人网络直接在点上显示专家名称

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#9]
个人网络里点的个数比较少，我们希望能看到每个点的医生标签在点上，且点的大小区分度能大写，现在大的专家的点并没有很大

**Comment by FreeZheng** [comment]
已扩大差距范围，由于点多的时候都显示名字不美观，现设置为总分大于100的点显示名字

**Comment by Medomino** [comment]
总分大于100的显示名字这个处理没问题。 点的大小目前没有和专家综合学术分关联（综合分数高的，点更大），另外专家名字的字体大小能否也和点的大小关联（点大的，名字字体也大些）

**Comment by Medomino** [comment]
个人网络筛选后，请只留下筛选后的点，现在的时间和强度筛选好像没有效果。

**Comment by FreeZheng** [comment]
目前点的大小就是根据总和学术分关联的，此类型图不支持文字缩放，触发筛选的时候会改变点颜色，以此更新

**Comment by Medomino** [comment]
现在的大小和学术分数的大小不一致，纪立农的学术分数最高，但是他的个人网络的点比很多点都小

**Comment by FreeZheng** [comment]
![image](https://user-images.githubusercontent.com/25632017/37816719-0e231448-2eaf-11e8-9469-4be745ca37e9.png)

**Comment by FreeZheng** [comment]
这是目前版本，没发现上面的问题

**Comment by FreeZheng** [comment]
已修复
