### ISSUE TITLE
设置可见性的普通用户内容显示问题

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#90]
账号：bing.xu
密码：123456 
1. 右上角的名称并不是账号设置时候的“账号展示名”，而是账号名
2. 竞争格局里最右边的图丢失
3. 仪表盘里的内容只显示可见性专家的内容，不是可见性里的专家，对该用户不可见 （也就是说该用户只能看见京蒙区和东北区的医生构成，其他区域不显示； 竞争格局里的内容也是他可见医生的图表； rising star 里只显示他能看见的医生，看不见的都不显示； 最新动态也一样） 

![image](https://user-images.githubusercontent.com/36838827/41265215-b24fcb3e-6e23-11e8-8e85-ff60c694c3ac.png)

4 筛选和上色只能看见自己所见医生的属性（京蒙区 和东北区）， 看不见的医生属性也显示会给用户造成困扰 
![image](https://user-images.githubusercontent.com/36838827/41265390-a2655012-6e24-11e8-838b-0f9becb34f62.png)

5 这样空行和空格的展示让人不太能接受，感觉系统坏了一样 
![image](https://user-images.githubusercontent.com/36838827/41265431-d3b1f4d6-6e24-11e8-8078-64ad29ebe441.png)

6 个性化合作里，不可见的医生不能显示在下面 
![image](https://user-images.githubusercontent.com/36838827/41265494-1f1aaa30-6e25-11e8-9cf3-adcf63b95fc9.png)

7 普通用户没有账号设置 
![image](https://user-images.githubusercontent.com/36838827/41265538-56da5b5a-6e25-11e8-8122-42ae4d9f9729.png)

**Comment by simple-hui** [comment]
问题7：普通账户 有账号设置。应该是只能编辑自己的密码

**Comment by Medomino** [comment]
但是问题7可以这样，然后点击还说操作成功，虽然实际上没成功。普通用户能否把右上那个“新增用户”去掉，不然会引起误会，谢谢 
![image](https://user-images.githubusercontent.com/36838827/41326490-c0ecb232-6ef1-11e8-8736-163ed790b376.png)

**Comment by simple-hui** [comment]
问题7 已修复 user用户去除新增按钮

**Comment by simple-hui** [comment]
问题1 已修复。显示展示名 display_name

**Comment by maqunboy** [comment]
4 解决

**Comment by FreeZheng** [comment]
2 已修复

**Comment by maqunboy** [comment]
6 已经修复

**Comment by maqunboy** [comment]
3已经修复

**Comment by Medomino** [comment]
其他看着都修复正常了，多谢。 这张图还有点问题， 未过滤

![image](https://user-images.githubusercontent.com/36838827/41398095-c7ae6b5e-6fe8-11e8-952f-3be19f5b690e.png)

**Comment by maqunboy** [comment]
已修复
