### ISSUE TITLE
创建用户后，无法显示在账户设置列表里，虽然用户创建成功

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#92]
测试账户 ： xuan.qi
密码：123456
列表里找不到上面这个账号
![image](https://user-images.githubusercontent.com/36838827/41326650-80a6916a-6ef2-11e8-9b6f-0fd0824eb810.png)

**Comment by simple-hui** [comment]
![image](https://user-images.githubusercontent.com/24288191/41329298-69764064-6eff-11e8-9196-88c7cc13f158.png)
创建账户的时候没有选择用户类型  及 是用 lu.zhang 创建的 xuan.qi 那么得给他选择user用户类型。现在登录zhanglu可以看到列表里有xuan.qi了。
