### ISSUE TITLE
 账户设置现在部门无法选择，另外用户列表能否增加分页，目前不知道建了几个账号

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#95]
测试账号： lu.zhang
密码： dia123456

![image](https://user-images.githubusercontent.com/36838827/41390087-c08ebd8c-6fc6-11e8-8305-c3cbdc5a6048.png)

**Comment by simple-hui** [comment]
部门在别的issure已修复。底部增加总条数。
