### ISSUE TITLE
数据统计里， Admin 不应该看见除了他自己的公司

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#96]
这个上次碰面的时候谈过， Admin 创建的用户都是他自己公司的， 如果不能只显示他自己的公司的话，公司这个选项对Admin 是不可见的。 只有superadmin 可以选择公司
测试账号： lu.zhang
密码：dia123456
![image](https://user-images.githubusercontent.com/36838827/41397789-dd9bd72c-6fe7-11e8-8294-de20523648eb.png)

**Comment by simple-hui** [comment]
已修复
