### ISSUE TITLE
在医生个人页面中，文章趋势显示需略调整

### ISSUE THREAD

**Issue by Medomino** [web-vue-auto/dev#99]
![image](https://user-images.githubusercontent.com/36838827/41635333-c937adaa-747a-11e8-9ca3-d4904ae9410b.png)
由下至上，请按照此顺序显示，其他作者，第一作者，通讯作者，这样最重要的通讯作者会显示在最上面，注意是通讯作者，不是通信作者

**Comment by simple-hui** [comment]
已修复
